### ISSUE TITLE
Creeper village [voxels] prices

### ISSUE THREAD

**Issue by vaptsiukas** [Darkosto/InvasionIssues#160]
Hi, enjoying this pack, but noticed smth.
From what I saw in streams, people are able to buy special armors, tools, etc from creepers. (ex. youtube StompTheBean  got key to the city for 1000, voxels:special_leggings2 for 1752 and so on)
I've found a village, and prices are way to high in comparison how much voxels you are able to get from creeper trading. Also tried few new worlds, every time is the same. Seems prices are fixed in config/voxels/prices.json file.

Some prices ex:
minecraft:dragon_breath'': 25000000
voxels:special_boots3": 160000
voxels:special_leggings2": 140000
minecraft:nether_star": 2000000000
voxels:specialsword_2": 150000

Each creeper has only 1k-3k voxels on him. 
Are these prices intended to be so high (not buy-able without cheating) or need to be fixed?

**Comment by GenDeathrow** [comment]
They were intended because players could become OP  with very few voxels. It makes more sense for them to be high so you will have to work to get the best items in the game. It was because of the youtube videos and streamers that this got changed. Especially after the fact that the armor would make you immune to all damage.

**Comment by vaptsiukas** [comment]
ok, got it! thank you for explanation :)

**Comment by witdy002** [comment]
I can get nether star via killing wither as per normal, but is there anyway to get dragon's breath at all?

thanks.
