### ISSUE TITLE
1.0.5 sleeping in bed enabled

### ISSUE THREAD

**Issue by vaptsiukas** [Darkosto/InvasionIssues#184]
Hi, don't know if this is intended but after 1.0.5 update I'm able to sleep. 1st time clicked on bed in new location (old world, just new base) to set spawn during night time - and.... I'm sleeping. Few times after that I clicked  on bed accidentally, and lost some days in this way. 
Sort of bug - this way you get harder raiders faster without technological progress to defend.

**Comment by ArcaniX5696** [comment]
I too noticed that sleeping was re-enabled, but since it's been raised as a conversation, I thought I'd chime in - I actually prefer that sleeping has been enabled.

Yes, this might cause you to "go through your days too quickly", however I think this is more of a "trade-off" that the player should have to work with.  Sleep and get day-time / avoid the night, but lose X hours of time because you slept.  If the concern is "accidental sleep", you can always cancel the sleep event before it actually "sleeps" and jumps to morning...

**Comment by Lost-Ninja** [comment]
It also means you can get out of continual rain for solar panels... :)

Sincerely hope this doesn't get reverted.

**Comment by Darkosto** [comment]
Fixed in 1.0.6
