### ISSUE TITLE
Genetics Reborn flight gene legitimately obtainable but disabled without warning

### ISSUE THREAD

**Issue by Hjaldar** [Darkosto/InvasionIssues#192]
The flight gene from Genetics Reborn is legitimately obtainable (steps below) but the gene is disabled in the configs, i.e. changed from default config. Please consider either re-enabling this ability or flagging the fact that it (and other legitimately obtainable genes) are disabled early in the Genetics Reborn quest line (Upgrades).

Steps to obtain flight gene:
1. Spawn a *lot* of Livestock Crates via air drop (bat seems quite rare).
2. Finally get a bat to spawn and run around for most of a MC day trying to catch it in a soul vial.
3. Convert broken spawner to bat spawner in soul binder.
4. Make a powered spawner for bats and scrape them for genetic material.
5. Build all Genetics Reborn machines and make flight gene.

**Comment by ImelchorI** [comment]
something similar bothered me with the silk touch enchantment aswell.

its legitemately obtainable via enchanted book from the ender io enchanter. but when i combined the book in an anvil with a pickaxe, it returned an unenchanted pickaxe.

all i wanted to do was move my redstone farm without crafting all the ore again : /

**Comment by GenDeathrow** [comment]
Silk touch has been turned off in the mid pack.

**Comment by ImelchorI** [comment]
i know it has been turned off. but you dont get a warning that its turned off. the book is still obtainable, and you can craft it with a tool in the anvil. only that you lose the book and the xp and get the unenchanted item.

why is it turned off anyways? by the time you get a silk touch tool, you probably already have a cobble gen anyways so its not like you can really cheese smooth stone or cobble right off the bat.

**Comment by GenDeathrow** [comment]
Well as far as a way to inform players it turned off, that's would have to be added into the mod that removes it. Basically like you said its turned off so you don't cheese it.  RNG could give you a book right when you spawn in. in a chest. Or tools you find have a chance of getting it.

**Comment by Darkosto** [comment]
I mean, this also takes into account that you make an assumption something is turned on/enabled in the first place. Which, in a pack like this, it's not. There are no other flight options available like angel rings, bats wings, etc. and the quest book doesn't lead you to a point to conclude flight exists through genetics. Assumptions in an overhaul modpack do not get you anywhere, and most questions are answered by the quest book. Hence the reason I spent hundreds of hours writing it.

Redstone not being movable is intended because you're meant to think about where you're placing it and take responsibility over your actions. 

While I understand these concerns, I'm only making 1 change and that's adding a text to the Silk Touch and Fortune books that say "Not Obtainable"
