### ISSUE TITLE
Hitbox on dogs too small

### ISSUE THREAD

**Issue by stats** [Darkosto/InvasionIssues#23]
The hitbox on dogs is either very small or very weird. Attacking it is very difficult and not consistent with other mobs.

**Comment by GenDeathrow** [comment]
When in-game Open your menu -> Click mod options -> Go to animalium -> Open Config -> turn on show hitboxes. Once you learn its hit box youll under stand it.

**Comment by stats** [comment]
I did more testing and the hit boxes can get wonky while the dogs are running. The hitbox can turn diagonal to the player and the dog's snout often extends past the hitbox boundaries. This results in player attacks which feel like they should be a hit resulting in a miss.

The titles of the buttons to enable the hit boxes and your statement that you need to learn the hitbox in order to combat the mob more than hints at a problem.

Early game there is very little counter play if a pack of dogs ends up getting aggroed. I do not think that results in healthy gameplay. It might be good later into the game when the player has the tools to fight back, but is oppressive early.

Ignoring hitbox issues the dogs speed and pack size are problematic. A possible solution would be, during days 0 to 3:

1. Limit the number of dogs that spawn to one.
2. Reduce the speed of the dogs (possibly to 75% of current speed)

The dogs should still present a challenge to players, but there should be more counter play during the first couple of days so that a player has a chance to learn how to deal the threat.

**Comment by GenDeathrow** [comment]
Ok, well let me explain than. It uses a different hitbox system ,because vanilla minecraft does not support mobs larger than one block in length. And is done this way, because if he had used vanilla hit boxes and increased the hit box to fit the size of the dog, Than dogs were able to hit though blocks. Players were getting killed while behind walls. 

That is because vanilla bases the hit distance on their hit boxes,  but does not check if blocks are in the way. I have watched many streamers play this and hit them fine. But with that said ppl are use to vanilla style hit boxes, and this throws them of. And yes they do jump sideways sometimes. Which is also based off the vanilla jump helper. 

As far as the amt of dogs that will be balanced next update. 

EDIT: had to edit first write was on mobile.
