### ISSUE TITLE
Problem Revolving around Gravestones and Genetics Reborn (And more)

### ISSUE THREAD

**Issue by Zenitheevee** [Darkosto/InvasionIssues#242]
So, Now.. It's become appearant that there are a few problems with each individual mod (Genetics Reborn not carrying over genes post death like it should, or else the Keep Inventory gene would be useless, which it totally actually is), And one of them affects servers heavily..

The Gravestones mod appears to have an interesting action where it duplicates a players inventory before deleting it, This becomes a problem with the introduction to soulbound items (A rare enchant to get naturally, and an expensive one without a table), Which get duplicated.. And both items get sent to the players inventory. Now, this becomes a bigger problem when you factor in that this allows players to turn Invasion into a 2 hour montage of people playing darksouls, rolling off cliffs for hte free ring at 50 deaths or something, Then making the game a breeze because they now have all items they need to use..

Also, Small side note, can we add/ask to add Packed Ice to the Void Resource Miner potential drop list?

**Comment by Darkosto** [comment]
[default: true]
 B:"Keep Inventory"=false

 Better keep some back up syringes if this is set to false. [default: true]
    B:"Keep genes on death"=false

That happens because I set them to be that way. Above are the values in the config file.

As for the soulbound issue (please make separate open-issues for multiple bug reports): The first half of your explanation, you make soulbound sound like a very difficult to come by enchant and then say people are duplicating everything to survive. I'm also surprised you even have items that are soulbound working in the first place, since Soulbound items have been deleted on death for the last few months. It sounds like those 50 deaths might for naught due to this bug. Gravestones have nothing to do with this, since it doesn't catch soulbound items (they stay in your inventory and gravestones doesn't grab them ever).
