### ISSUE TITLE
Modpack is SO difficult _ please think about the new players

### ISSUE THREAD

**Issue by doombot93** [Darkosto/InvasionIssues#244]
What is the point of this modpack? Its literally to the point that you can't make it past day 3 without your base being swarmed by mobs and dying.

A few questions:

1) WHY CAN MOBS BUILD/MINE TO YOU!? Minecraft mobs are supposed to be stupid and easy to fight, not as difficult as this, makes the modpack lose its fun value

2) Why make water travel impossible? I've died more times than I can count to dying to pirahanna's jumping out of the water

3) Why do torches catch fire? That makes wood practically useless in this pack because you put down a torch and your game lags out from burning down a forest (happened to me several times) 

4) No one enjoys this difficult packs, try to tone done all the nerfs because progression sucks in this pack.

I'm done wasting my time on the commenting. Bye.

**Comment by vadis365** [comment]
BOO-HOO!
Try playing something easier like Dark souls 3 - you may like it.
Bye Felicia!

**Comment by Darkosto** [comment]
Here's something that may appeal more to your specific playstyle: https://hellokittygamesfree.com/

Maybe you'll find something a bit more enjoyable on that site.  Good luck and have fun!

**Comment by MrComputerGhost** [comment]
It's like Invasion was made with the intent of being a difficult pack or something. Never would've guessed it could've been hard.

**Comment by Hanger84** [comment]
Wait a second. What makes you so ENTITLED that no one can make a difficult pack that THEY enjoy, and share it with others who might enjoy it? HOW DARE YOU assume that everyone WANTS easy packs with the same playstyle every single time. HOW DARE YOU tell someone to make it 'easy' because YOU are to lazy/ignorant to think outside the box and learn a new game mechanic. And lastly: YOU CHOSE to play the pack, no one forced you to. If YOU don't like it, that does NOT mean that NO ONE likes it. Who the hell gave you the right to speak on my behalf? Who the hell gave you the right to speak on the behalf of an entire community?!?!  If you don't like it, don't play it! Don't whine and complain because its not something you like. Grow a pair and stop playing the pack and switch to one that lets you play on easy mode!

**Comment by Funwayguy** [comment]
A few replies:

1. I thought players got good instead of complaining on the internet when they experience a new challenge.

2. I've heard there are things called bridges, boats, armor and weapons. Also refer to point 1

3. ERMAGERD I CAN ONLY MAKE WOOD HOUSES... really? Is that the extend of your creativity

4. No one enjoys reading your personal issues with the pack. Try to tone down the entitlement and stupidity

**Comment by kylecourounis** [comment]
It was meant to be difficult. Apparently you are one of those people that thinks every pack needs to be tailored to them. LOLOLOL

**Comment by pip69** [comment]
The configs and difficulty levels are not locked.  It's easy to adjust for your play style.
I made things super easy for myself the 1st time I played, but each time I restart I make it less easy than the previous time.  

Raiders themselves are easier to fight than regular mobs,  They're more like the big bad wolf to you being the 3 little pigs.

**Comment by Darkosto** [comment]
Just a quick update on this issue,

**Comment by Funwayguy** [comment]
Missed the most important one!
