### ISSUE TITLE
HQM shows 0 quests upon logging back in

### ISSUE THREAD

**Issue by Archimabees** [Darkosto/InvasionIssues#25]
I downloaded the server files and tried making a server. The serverstart and settings batch files were missing so I pretty much copy pasted from my Skyfactory 3 server. When I first login and do /hqm enable everything works fine until my friend and I log off and back in to fix the quest book teams sync issue. When we log back in the book shows 0 quests. We did some testing and it happens whether we're in a team or not.

**Comment by InfernoParrot** [comment]
I have the same problem. Played with a friend on a LAN server over hamachi for about 6 hours and now the quest book shows 0 on everything.
Creating a new single player world does not fix the issue. I just start with 0 quests

**Comment by InfernoParrot** [comment]
json quest files get deleted upon starting the wold, after a crash, caused by the player being in a party.
This is the issue boiled to a single sentence. I'm continuing debugging to determine if there is anything more to it.
Steps I used to reproduce it consistently 3 times already:
Started world
unlocked achievemnts
made a party
closed world
started world
game crashed
started game again
started world
while loading files dissapeared from hqm folder
game is now stuck at Loading


From what I gather so far, the issue is caused by the party creation. After the initial crash, the files are still there, but when attempting to start the world after that, they get deleted.
Screenshot depicts which files get deleted, showing newly generated world on the left and corrupted world on the right
![explorer_2017-03-28_14-01-16](https://cloud.githubusercontent.com/assets/18116041/24402981/a400071c-13c3-11e7-84ae-8d0f8522bbb6.png)

**Comment by Liloa** [comment]
I played forever last night and when I logged back in im having the same issue
<img width="649" alt="screen shot 2017-03-29 at 11 05 42 am" src="https://cloud.githubusercontent.com/assets/8813897/24476618/b761b8d0-146f-11e7-8067-e0d5ab04a357.png">

**Comment by Yorkforce** [comment]
We are also experiencing this issue in 1.0.2, it seems to trigger on the 5th team and above thats created (for us anyways but it could be team 4 or earlier, we just had a report from the player who created the 5th team) which then results in the player who tried to create the team having no quests when they log back in. Removing everything from and after the "id":5 team entry from the teams.json file will fix the 0 quest problem but the player will lose quest progression and have to start from the beginning.

Not sure if that helps.
