### ISSUE TITLE
fortune, silk touch and the dragonslayer

### ISSUE THREAD

**Issue by Arkeus121** [Darkosto/InvasionIssues#250]
Ok, so when i try to enchant a pickaxe with fortune or silk touch it will unenchant itself when it's moved to my inventory (I used an anvil and a book). Not sure if it's a bug or intended (please let me know... anyone), if it's intended a warning would be nice.

Furthermore, when enchanting the first iteration of the dragonslayer ('Black Ultra Greatsword') in the enchanting table it doesn't work at all (once again, not sure if it's a bug). However, in the anvil I noticed that it will accept some enchants such as sharpness and looting, but not some others (I think that are mod introduced) such as xp boost.

**Comment by GenDeathrow** [comment]
Silk touch has been removed from the pack. But because things can get random  enchants they have to be removed on the item themselves. 1.0.6 will have more information to the player in tool tips if that enchant is removed.  

The dragonslayer seems like a mod issue. May not hurt to report that one to the author.

**Comment by Darkosto** [comment]
https://github.com/Darkosto/InvasionIssues/issues/192 

This is intended.
