### ISSUE TITLE
[Suggestion] Few things to balance things.

### ISSUE THREAD

**Issue by beringtom** [Darkosto/InvasionIssues#271]
Clay is life, without clay life can't be sustained.

1) Ability to grind hardened clay into clay or bricks would be much welcome as clay is hard to come by atm.
*edit* Maybe grinding sand into some dust and craft with water to make 1. clay (not a block)
2) Medikits and Enchanted medikits needs their healing amount buffed, we tweaked our kits is healing ½bar and 1bar with 10 uses each to balance them.
3) Drones, I suggest removing the explosions on the saw blades due to how much dmg they do.
4) Torches starting fires, now I love the idea, but when your village burns down because the builder can't use small torches it sucks, might consider turning that off.

This is mostly a sidenote but would love to see more "modern city" buildings to explore to keep to the invasion theme.

Thank you for the many hours of gameplay so far.

**Comment by SystemCollapse** [comment]
The explosions on the sawblades can be turned off in the config. It was the first thing I did when the pack was updated. Very easy Source of clay is Flower Pots that can be found using the strainers then ground down in a sag mill.

**Comment by beringtom** [comment]
I should have stated that this was ment as a global suggestion for balance, not just for us.
We already disabled the exploding blades as the riding laser creepers that spawn in light is more then enough to keep everyone busy. While flower pots might be a fine way of getting clay there simply ain't any easy way to see that you actually CAN get them from the strainers and therefor my 1.st suggestion.

**Comment by Darkosto** [comment]
1. Clay has always been turned on to spawn all over the world, not just in typical vanilla locations. I have no issue in any playthroughs finding more than enough clay. I don't find any reason to add any more recipes to obtain it. This is a exploration pack, much of the experience lies in finding resources. I've made way too many changes to recipes to allow people to grind out resources from within their base, which is completely against the narrative this pack was even intended to have.
2. I think medkits give plenty of healing, if you need more I would reccomend locating more methods/items for healing.
3. I have no problem with the damage the drone sawblades, I tend to never worry about this since I use ranged attacks or turrets to deal with them.
4. Not one builder has burned down a village I've created using Minecolonies due to the fact that only torches placed by a player in survival turn in "burning" torches. 

Thank you for the suggestions, but I honestly don't agree with these changes. I've made more than enough changes against my initial design of the pack due to players requesting more "balance". While I appreciate you taking the time to come here and voice your opinion on what you feel would benefit the pack, I have to respectfully disagree. I don't feel these changes will do anything except compromise the integrity of the pack I made for the players wishing for a truly difficult/hardcore experience. 

There are 3 huge modern style cities that always spawn in the pack. Also, I think you may be misunderstanding some of the intention of the pack, it's less meant to be a futuristic style "real-world" environment. But, the remains of a minecraft server left unintended for a long time. Not all minecraft builders are going to build the same style or even modern houses/builds. The different styles are reflective of the different types of builds people would make if on a server.

Thanks for the suggestions!
