### ISSUE TITLE
Very High Spawn Rate in 1.07

### ISSUE THREAD

**Issue by Mikhaila666** [Darkosto/InvasionIssues#291]
We just upgraded to 1.07 and reset the world, and the spawn rate is way, way to high, making the game unplayable. Mobs spawn all around in the day as you move, with usually a couple of dozen on the screen. Pausing at all brings this way up. Staying in a building at night is nearly impossible as they set them on fire, and the bulk of buildings are flammable. This is only day 11, and we put it on easy. 

Some of us played a ton of Bloodnbones and other hard packs, and we were on raider level 26 on the old world, so we should be able to handle day 11 :)  But it's pretty much unplayable.

Is there a config to turn down the overall spawn rate somehow?

**Comment by Degenerecy** [comment]
I've noticed that the spawns do happen quite frequent.  However going to a Peninsula style area surrounded by water can limit the amount of mobs tremendously.  Day 60+ and maybe every 10 min a Raider or in my case Creeper Dino's will come near about every 30min.  Which my single laser turret annihilates them in a few seconds.

Basic is to never go in a prebuilt structure, they are empty for a reason ;)

Also check out https://www.reddit.com/r/feedthebeast/comments/62831p/any_tips_for_the_new_invasion_pack/
It has a few good tips and tricks.

**Comment by liorrozen** [comment]
I am also seeing very high spawn rates on day 0 after updating to 1.0.7 (from 1.0,5). For me, raiders are less of the issue; Already on 3 fresh instances I'm encountering packs of 4-5 dogs and/or rats on day 0.

**Comment by GenDeathrow** [comment]
Ok to clear this up. Spawns have not changed in 5 updates.  These are the same as always. Mobs can spawn below sea level and can move up to the surface. Moba are suppose to set buildings fire.. it's a mechanic on purpose. 

Thier is a  max number hostile  that can spawn in vanilla. That has not changed in this pack that means 70 mobs can be loaded at one time. Raiders spawn during daylight, but move 40% slower. I have noticed some worlds have different spawning. 

The pack is not unplayable. If this was true their  wouldn't have been countless number of ppl who have beat it. 

EDIT: Their is no config to change spawning rates as it is handled by vanilla. all you can do is change weights.. which means you can make one mob spawn more than other mobs. you cant change the amount of mobs you see as that is handled by vanilla minecraft. Which is why  I say spawn rates have not changed. 

Also the dogs and rats spawning on day 0 has happened randomly, I'll look into it. but rats are not hostile during day time.

**Comment by Yorkforce** [comment]
Just to confirm what other have been saying, the spawn rates have increased significantly in 1.0.7, we have had many players mention it in the server chat, there is definitely something different since 1.0.5.

**Comment by GenDeathrow** [comment]
Spawn cap and rate is vanilla code. I have no control over how many raiders spawn at all. The amout of spawns per Chunk is the same as zombies. Also servers spawn caps increase based on players. So more raiders have potitial of spawning. Could I cap mobs yes but it's alot of extra work I that could break compatibility with other mobs, and this is the same with vadis's mobs. Between 1.0.5 & 1.0.7 I change very few things. Most were a couple ai fixes and fixing logs getting up to 8GB. 
It is a hardcore pavk

**Comment by Yorkforce** [comment]
Sorry Gen it wasn't a criticism or an accusation that anyone had intentionally or specifically done anything, just reporting that we had noticed a change for some reason, it could even be forge related as that was updated to 2281. Server wise all we can say is that player numbers haven't increased or changed drastically, nor have we made any other changes.

I do fully understand its a hardcore pack, but it does feel as though the spawn rates are pretty extreme in this version, to the point where players who have been playing since the pack came out have mentioned it's become abit frustrating (beyond the normal difficulty that comes with a modpack like this that is).

I will look to see if we can do anything on our side to lower spawn rates and thanks for the console spam fix! that was a major problem in 1.0.5 and we are very relieved and grateful you guys got it fixed :)

**Comment by Mikhaila666** [comment]
My guys think it is something to do with Sponge. 


And as York said, this isn't a criticism, it's an observation. We made a 1.05 world and played up to level 26 on our server. There was a lot of interest generated so we started the world over and updated to 1.07. The spawn rate was just very increased, with mobs spawning very very fast around a player. You don't get killed by 1 pirahna, they hit you in groups of 10. Lots of dogs, dozens of raiders. 


we mucked with things to get the spawn rate down a bit, and compensated by changing configs to keep the difficulty down a bit longer so more people can join and start up. So it's working ok for now. 



-----Original Message-----

**Comment by Yorkforce** [comment]
It could be actually Mikhaila, we did update spongeforge when we did the version update. I'll try reverting back to the previous version tomorrow and reply back here with any insight.

**Comment by GenDeathrow** [comment]
Sorry, if I sounded rude about it, Its just been reported on ever version that has been released and I have to explain it each time. So I apologize for sounding rude. 

It wouldn't surprise me if Sponge was the culprit at all. Ive had way too many issues with Sponge, its why mod devs wont support sponge, mainly because sponge should work with forge and in turn work with forge mods.

**Comment by GenDeathrow** [comment]
Other than me play testing, I have watched streams on twitch that haven't had any increase in spawn rates. they seem pretty normal to me.

**Comment by Yorkforce** [comment]
Yep I get the reluctance with sponge, unfortunately it's the only way we can manage a server properly especially in 1.10, else the customer service aspect would be completely unmanageable and in turn the players would go elsewhere where there is a better playing experience. But as you say it comes with its own problems.

And no worries, I understand how frustrating it can be dealing with tons of issues and the such, you're doing an awesome job! (as are alot of modpack devs), i can only tip my hat in respect :)

**Comment by Mikhaila666** [comment]
Yep, that's our issue. Need it to run the servers, but it adds all sorts of little problems. And hard to figure out what is from sponge, and what isn't.



-----Original Message-----

**Comment by Degenerecy** [comment]
Just to point out the spawn rate was changed in 1.0.5 to 1.0.7.  From .75 to .78 but this seems too small of a change to cause the OP's issue's.

**Comment by GenDeathrow** [comment]
What setting are you talking about degenercy?

**Comment by Degenerecy** [comment]
Config > raiders > settings.
Mulitply raiders speed during Daytime...
That is the only thing I seen regarding spawns(that changed).

**Comment by liorrozen** [comment]
@Degenerecy I do not believe that these settings deal with the spawn rate, rather with the raiders *movement speed*. I think that the issue we are discussing here is the *number of mobs that spawn* and not their behavior once they are already in the world.

**Comment by Degenerecy** [comment]
Yea I just noticed the wording, few settings down was the spawn weights which are unchanged.

**Comment by GenDeathrow** [comment]
Yeah thats movement speed. also the way spawn weights work is it takes all mobs spawn weights.. for example. [10(raiders) + 5(drones) + 1(bears)+ 8(fish) = 24   = 10(raiders) / 24(total weight) = .41% chance to spawn a raider over other mobs  ] weight is only a percentage to spawn it doesn't control total mobs spawned but more of a chance to spawn that particular mob when something has to spawn.
