### ISSUE TITLE
The player im playing lan whit cant se the quests

### ISSUE THREAD

**Issue by thecattgod** [Darkosto/InvasionIssues#34]
wen im playing whit my brother he cant see the quests in the quest book if you can help i whould really like it

**Comment by ByteTemplar** [comment]
Did you check these:

* When setting up HQM teams, players need to log off and back on 1 time due to a small sync issue. This will allow them to interact with quests correctly.

* If you're playing Coop, make sure to note mobs get more difficulty as time progresses. Make sure to shut the server down so you don't log back into insanely difficult enemies.

**Comment by Darkosto** [comment]
Well, HQM currently does not work properly in LAN mode. This is possibly being fixed. We'll see if this can be done in the future, for now there's not much I can do.

**Comment by jamzam90** [comment]
Hey @Darkosto have you tried better questing by any chance?
