### ISSUE TITLE
Server crash - epicsiegemod

### ISSUE THREAD

**Issue by Yorkforce** [Darkosto/InvasionIssues#49]
Ran into this issue tonight:
https://pastebin.com/BLPwP3Qr

I believe it's related to mobs digging, after removing the mobs listed under the S:"Digging Mobs" entry in the config, the crash stopped.

This may be related to SpongeForge as I noticed this on funwayguy's github:
https://github.com/Funwayguy/Epic-Siege-Mod/issues/58

If so I'm happy raise the issue with them if you prefer

**Comment by Darkosto** [comment]
I'll let @Funwayguy know about this, thank you!

**Comment by GenDeathrow** [comment]
To me seems to be more of a sponge issue. Infact sponge has issues with a lot of mods. Most devs wont fix sponge issue's / or look at it unless it can be replicated in forge it self.

**Comment by Funwayguy** [comment]
As @GenDeathrow says, I have no intention of looking into this any further unless it can be recreated in Forge without the use of Sponge, sorry.

**Comment by GenDeathrow** [comment]
I guess end note would be post in Sponge and link it here.

**Comment by Yorkforce** [comment]
Will do, thanks for checking guys

**Comment by bookerthegeek** [comment]
@Funwayguy according to the issue over at sponge it seems that the code [here][1] could be redone so that it is not using reflection to replace the entity AI tasks instance with your own proxy.  

Yes this issue came about on a Sponge server, but might not only be a Sponge issue. As any other mod that uses the AI tasks instance BEFORE you replace it entirely would also crash as there is no guarantee that your handler will run before the other mods.

@bloodmc would most likely be able to give a better explanation.

[1]:https://github.com/Funwayguy/Epic-Siege-Mod/blob/1.10/src/main/java/funwayguy/epicsiegemod/handlers/MainHandler.java#L61

**Comment by Funwayguy** [comment]
I am well aware of AIs added/removed from the list of tasks before the proxy replacement is implemented. It is handled within the proxy's constructor to make sure those additional edits are also carried over. The proxy also inherits from the original making it compatible with most existing mods without explicit knowledge about the proxy version as long as they aren't trying to cache the old instance (not particularly sure why you'd need to anyway). I haven't once received a compatibility issue with another mod arising from the use of this proxy class besides Sponge servers.

The reflection hook is necessary to intercept changes to AI tasks post-spawn such as Skeletons switching between ranged and melee otherwise I would have to periodically make the checks manually which would cause a noticeable performance hit to TPS.

So again, I will NOT be changing ESM's AI hook unless I can see a non-Sponge recreation of this issue.
