### ISSUE TITLE
raider spawn in very large groups

### ISSUE THREAD

**Issue by Shadow77388** [Darkosto/InvasionIssues#85]
i played in 1.0 and made a multiplayer world and the amount of mobs that were spawning was overwhelming at least 20 around me at any time. i did update to the 1.2 version with a clean start on the server and client side and the mobs were still a lot. i did see a drop in wolves but the raiders were everywhere as soon as i spawned, i did watch dw20s game play and he has 1-4 raiders at any time attacking not 20 and this is mobs that are withing 30 blocks of me not around my view distance.

**Comment by GenDeathrow** [comment]
DW20 is on an old version that had some spawning issues. That were partially fixed in 1.0.2 and will be fixed in 1.0.3. But raiders are suppose to spawn in large numbers at all times of the day

Raider run much slower during th day. Which makes it eaiser to get a round. The whole point of the pack was to keep moving, build defense and get off the planet. They are spawning by normal minecraft rules which means 24 blocks away. 

They also have special ai that seeks the player out, and the can spawn in lighted levels.. 1.0.3 will pervent spawns near blocks that give off light levels. Just like vanilla torches stop spawns.

**Comment by Darkosto** [comment]
This should be fixed in 1.0.3, upon updating let us know if it works better for you.

**Comment by Sabrewulf** [comment]
Wait, the objective is keep moving and build defence? But the defence is static.

**Comment by GenDeathrow** [comment]
There is a comma there now, by keep moving when you gathering resources.. And you build your base with defense so you have a place to craft everything to get off the planet.
